const experience = [
  {
    id: 7,
    title: "Frontend Developer",
    employmentType: "Contract",
    companyName: "Neuronhub",
    url: null,
    locationType: "Remote",
    startDate: new Date(2025, 4),
    endDate: "Present",
    description: [
        "Built user-facing features using React.js, TypeScript, React Hooks, and Chakra UI",
        "Integrated with back-end services via GraphQL",
        "Delivered both major features and small UX improvements",
    ],
  },
  {
    id: 6,
    title: "Web Developer",
    employmentType: "Staff member",
    companyName: "Greenatom",
    url: "https://greenatom.ru/",
    locationType: "Remote",
    startDate: new Date(2024, 7),
    endDate: new Date(2025, 4),
    description: [
      "Developed and maintained corporate websites and internal services using Bitrix, PHP, JavaScript, SCSS, and HTML",
      "Participated in the development of 3 corporate websites and 6 internal services",
      "Implemented responsive and accessible UI components",
    ],
  },
  {
    id: 5,
    title: "Frontend Developer",
    employmentType: "Contract",
    companyName: "Momentum",
    url: "https://www.givemomentum.com/",
    locationType: "Remote",
    startDate: new Date(2024, 7),
    endDate: new Date(2025, 2),
    description: [
      "Built user-facing features using React.js, TypeScript, React Hooks, and Chakra UI",
      "Integrated with back-end services via GraphQL",
      "Delivered both major features and small UX improvements",
      "Proactively identified and reported bugs, tested functionality from an end-user perspective",
      "Collaborated closely with designers, product managers, and engineers across teams",
    ],
  },
  {
    id: 4,
    title: "Frontend Developer",
    employmentType: "Freelance",
    companyName: "Momentum",
    url: "https://www.givemomentum.com/",
    locationType: "Remote",
    startDate: new Date(2021, 10),
    endDate: new Date(2022, 10),
    description: [
      "Participated in the development and maintenance of a portal for creating custom websites" +
        " using a CMS approach.",
      "Contributed to the development and maintenance of the company's website.",
      "Took part in the development of a donation collection website.",
      "Developed websites using HTML, CSS, JavaScript, React.js and Chakra UI.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development.",
    ],
  },
  {
    id: 3,
    title: "Frontend Developer",
    employmentType: "Full-time",
    companyName: "SMART WORLD",
    url: "https://smartworld.team/en",
    locationType: "On-site",
    startDate: new Date(2021, 7),
    endDate: new Date(2021, 10),
    description: [
      "Conducted refactoring for two websites and migrated them from a CMS system to Vue.js.",
      "Implemented the use of the mobile-first approach within the company's web development" +
        " processes.",
      "Developed and implemented style guides within the company.",
      "Participated in the development of materials for internal conferences.",
      "Modified project designs to prioritize user experience (UX).",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
  {
    id: 2,
    title: "Frontend Developer",
    employmentType: "Freelance",
    companyName: "what. AG",
    url: "https://what.digital/",
    locationType: "Remote",
    startDate: new Date(2020, 5),
    endDate: new Date(2021, 7),
    description: [
      "Developed, updated, and maintained websites for renowned brands, educational " +
        "institutions, government agencies, and online stores using CSS, HTML, JavaScript, " +
        "and DjangoCMS.",
      "Successfully participated in the development, updating, and maintenance of 11 " +
        "projects during my employment.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
  {
    id: 1,
    title: "Frontend Developer",
    employmentType: "Volunteering",
    companyName: "Effective Altruism",
    url: "https://eahub.org/",
    locationType: "Remote",
    startDate: new Date(2021, 1),
    endDate: new Date(2021, 4),
    description: [
      "Refactored the profile page using CSS, HTML, and JavaScript.",
      "Improved the design and UX.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
];

export { experience };
