const experience = [
  {
    id: 6,
    title: "Frontend Developer",
    employmentType: "Freelance",
    companyName: "Momentum",
    url: "https://www.givemomentum.com/",
    locationType: "Remote",
    startDate: new Date(2021, 10),
    endDate: new Date(2022, 10),
    description: [
      "Participated in the development and maintenance of a portal for creating custom websites" +
        " using a CMS approach.",
      "Contributed to the development and maintenance of the company's website.",
      "Took part in the development of a donation collection website.",
      "Developed websites using HTML, CSS, JavaScript, React.js and Chakra UI.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development.",
    ],
  },
  {
    id: 5,
    title: "Frontend Developer",
    employmentType: "Apprenticeship",
    companyName: "Practicum by Yandex",
    url: "https://practicum.yandex.ru/",
    locationType: "Remote",
    startDate: new Date(2021, 10),
    endDate: new Date(2022, 1),
    description: [
      "Implemented three landing pages using CSS, HTML, and JavaScript.",
      "Applied web development skills to create interactive and engaging user interfaces.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
  {
    id: 4,
    title: "Frontend Developer",
    employmentType: "Full-time",
    companyName: "SMART WORLD",
    url: "https://smartworld.team/en",
    locationType: "On-site",
    startDate: new Date(2021, 7),
    endDate: new Date(2021, 10),
    description: [
      "Conducted refactoring for two websites and migrated them from a CMS system to Vue.js.",
      "Implemented the use of the mobile-first approach within the company's web development" +
        " processes.",
      "Developed and implemented style guides within the company.",
      "Participated in the development of materials for internal conferences.",
      "Modified project designs to prioritize user experience (UX).",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
  {
    id: 3,
    title: "Frontend Developer",
    employmentType: "Volunteering",
    companyName: "Effective Altruism",
    url: "https://eahub.org/",
    locationType: "Remote",
    startDate: new Date(2021, 1),
    endDate: new Date(2021, 4),
    description: [
      "Refactored the profile page using CSS, HTML, and JavaScript.",
      "Improved the design and UX.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
  {
    id: 2,
    title: "Frontend Developer",
    employmentType: "Freelance",
    companyName: "what. AG",
    url: "https://what.digital/",
    locationType: "Remote",
    startDate: new Date(2020, 5),
    endDate: new Date(2021, 7),
    description: [
      "Developed, updated, and maintained websites for renowned brands, educational " +
        "institutions, government agencies, and online stores using CSS, HTML, JavaScript, " +
        "and DjangoCMS.",
      "Successfully participated in the development, updating, and maintenance of 11 " +
        "projects during my employment.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
  {
    id: 1,
    title: "Frontend Developer",
    employmentType: "Internship",
    companyName: "MetaLamp",
    url: "https://metalamp.ru/",
    locationType: "Hybrid",
    startDate: new Date(2018, 3),
    endDate: new Date(2019, 1),
    description: [
      "Successful implementation of three projects, including a UI kit, a 2D game, " +
        "and a landing page website.",
      "Implemented website layouts based on Figma designs.",
      "Tested and ensured website compatibility across various browsers and devices.",
      "Cross-browser responsive web development, with a mobile-first approach.",
    ],
  },
];

export { experience };
